# Site settings
title: Read My Mind
header-img: img/home-bg.jpg
email: bill@billglover.com
copyright_name: Anosognosia Press
description: "Programming and prose."
baseurl: ""
url: "http://billglover.com"
twitter_username: I_Write_Fiction
github_username:  ScriptGadget
facebook_username:
email_username:  bill@ybillglover.com
linkedin_username: billglover

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-1601268-12

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
